{
    "name": "Odoo Passport and visa Services",
    "version": "12.0",
    'author': 'Pragmatic Techsoft Pvt. Ltd.',
    "website": "http://www.pragtech.co.in",
    "description": """Passport Booking and Visa Booking Service""",
    "depends": ["base", "product", "sale", "account", "crm"],
    "category": "Generic Modules",
    "data": [
        "views/passport_demo_data.xml",
        "wizard/passport_journal_entry_view.xml",
        "wizard/visa_journal_entry_view.xml",
        "views/passport_sequence.xml",
        "views/passport_view.xml",
        "views/visa_view.xml",
        "views/tour_visa_report.xml",
        "views/report_passport_booking.xml",
        "views/passport_visa_report.xml",
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    "active": False,
    'license': 'OPL-1',
}
